version: "3"
services:
   mosquitto-service:
      image: eclipse-mosquitto
      restart: always
      ports:
         - 1883:1883
      volumes:
         - ./mosquitto:/mosquitto/config
   coordinator-service:   
      image: asperandio/home-app
      restart: always
      ports:
         - 5900:5900
      depends_on:
         - "mosquitto-service"